export default [
  {
    text: "Buku",
    sub: [
      {
        text: "Agama & Filsafat",
        sub: [
          { text: "Buddha" },
          { text: "Filosofi" },
          { text: "Filsafat" },
          { text: "Hindu" },
          { text: "Islam" },
          { text: "Kepercayaan" },
          { text: "Khong Hu Chu" },
          { text: "Kristen & Katolik" },
          { text: "Spiritual" },
        ],
      },
      {
        text: "Arsitektur & Desain",
        sub: [
          { text: "Bangunan" },
          { text: "Codes & Standars" },
          { text: "Dekorasi & Ornamen" },
          { text: "Desain Dapur" },
          { text: "Desain Kamar" },
          { text: "Desain Ruang Keluarga" },
          { text: "Desain Ruang Tamu" },
          { text: "Desain Rumah" },
          { text: "Interior & Eksterior" },
          { text: "Metode & Material Bangunan" },
          { text: "Taman" },
        ],
      },
      {
        text: "Buku Import",
        sub: [
          { text: "Agriculture" },
          { text: "Art & Novel" },
          { text: "Child & Teenager" },
          { text: "Computer" },
          { text: "Economy" },
          { text: "Femininity" },
          { text: "Health" },
          { text: "Hobby & Interest" },
          { text: "Language" },
          { text: "Law" },
          { text: "Management & Business" },
          { text: "Medical" },
          { text: "Political Social" },
          { text: "Psychology & Education" },
          { text: "Reference & Dictionary" },
          { text: "Religion & Philosophy" },
          { text: "School Book" },
          { text: "Secretarial" },
          { text: "Self Development & Career" },
          { text: "Technique" },
          { text: "Tourism & Map" },
        ],
      },
      {
        text: "Buku Remaja dan Anak",
        sub: [
          { text: "Cerita Anak" },
          { text: "Dunia Pengetahuan" },
          { text: "Keterampilan Anak" },
          { text: "Komik" },
        ],
      },
      {
        text: "Buku Sekolah",
        sub: [
          { text: "Bimbingan Belajar" },
          { text: "Buku SD Kelas 1" },
          { text: "Buku SD Kelas 2" },
          { text: "Buku SD Kelas 3" },
          { text: "Buku SD Kelas 4" },
          { text: "Buku SD Kelas 5" },
          { text: "Buku SD Kelas 6" },
          { text: "Buku SMA Kelas 1" },
          { text: "Buku SMA Kelas 2" },
          { text: "Buku SMA Kelas 3" },
          { text: "Buku SMP Kelas 1" },
          { text: "Buku SMP Kelas 2" },
          { text: "Buku SMP Kelas 3" },
          { text: "Kumpulan Soal SD" },
          { text: "Kumpulan Soal SMA" },
          { text: "Kumpulan Soal SMP" },
        ],
      },
      {
        text: "Hobi",
        sub: [
          { text: "Alam" },
          { text: "Fotografi" },
          { text: "Hewan Peliharaan" },
          { text: "Hiburan" },
          { text: "Humor" },
          { text: "Keterampilan Anak" },
          { text: "Kuliner" },
          { text: "Musik & Lagu" },
          { text: "Olahraga" },
          { text: "Permainan" },
          { text: "Seni" },
          { text: "Tanaman" },
          { text: "Travel" },
        ],
      },
      {
        text: "Kedokteran",
        sub: [
          { text: "Farmasi" },
          { text: "Kedokteran Spesialis" },
          { text: "Kedokteran Umum" },
          { text: "Kesehatan" },
          { text: "Psikiatri" },
        ],
      },
      {
        text: "Kewanitaan",
        sub: [
          { text: "Bimbingan Orang Tua" },
          { text: "Busana" },
          { text: "Kecantikan" },
          { text: "Kehamilan & Menyusui" },
          { text: "Nama-nama Bayi" },
          { text: "Pendidikan Keluarga" },
          { text: "Resep Makanan & Minuman" },
        ],
      },
      {
        text: "Komputer & Internet",
        sub: [
          { text: "Database" },
          { text: "Design Graphics" },
          { text: "Hardware" },
          { text: "Internet & Web" },
          { text: "Microsoft Office" },
          { text: "Mobile & Gadget" },
          { text: "Programming" },
          { text: "Sistem Operasi" },
          { text: "Social Media" },
        ],
      },
      {
        text: "Majalah",
      },
      {
        text: "Novel & Sastra",
        sub: [
          { text: "Fantasi" },
          { text: "Kisah Nyata" },
          { text: "Misteri" },
          { text: "Novel Indonesia" },
          { text: "Novel Remaja" },
          { text: "Novel Terjemahan" },
          { text: "Puisi" },
          { text: "Roman" },
          { text: "Science Fiction" },
        ],
      },
      {
        text: "Pengembangan Diri & Karir",
        sub: [
          { text: "Kesuksesan" },
          { text: "Leadership Kepemimpinan" },
          { text: "Self Help" },
        ],
      },
      {
        text: "Pengetahuan",
        sub: [
          { text: "Astronomi" },
          { text: "Bahasa" },
          { text: "Biologi" },
          { text: "Ekonomi" },
          { text: "Elektro & Elektronik" },
          { text: "Ensiklopedia" },
          { text: "Fisika" },
          { text: "Geografi" },
          { text: "Geologi" },
          { text: "Hukum" },
          { text: "Ilmiah" },
          { text: "Kesekretariatan" },
          { text: "Kimia" },
          { text: "Manajemen" },
          { text: "Matematika" },
          { text: "Mesin" },
          { text: "Pariwisata" },
          { text: "Pengetahuan Umum" },
          { text: "Perhotelan" },
          { text: "Perikanan" },
          { text: "Perkebunan" },
          { text: "Perpajakan" },
          { text: "Pertanian" },
          { text: "Peta & Bola Dunia" },
          { text: "Peternakan" },
          { text: "Psikologi" },
          { text: "Sipil" },
          { text: "Statistik" },
          { text: "Teknik" },
        ],
      },
      {
        text: "Sosial Politik",
        sub: [
          { text: "Biografi" },
          { text: "Komunikasi" },
          { text: "Lingkungan Hidup" },
          { text: "Politik" },
          { text: "Sejarah" },
          { text: "Sosial Budaya" },
          { text: "" },
        ],
      },
    ],
  },
  {
    text: "Dapur",
    sub: [
      {
        text: "Bekal",
        sub: [
          { text: "Bekal Lainnya" },
          { text: "Botol Minum & Termos" },
          { text: "Cetakan Bento" },
          { text: "Cup Bento" },
          { text: "Kotak Makan & Rantang" },
          { text: "Partisi Bento" },
          { text: "Tas Bekal" },
          { text: "Tas Botol" },
          { text: "Tusuk Bento" },
        ],
      },
      {
        text: "Food & Drink Maker",
        sub: [
          { text: "Alat Penghias Kue" },
          { text: "Biscuit & Cookie Maker" },
          { text: "Cake Maker" },
          { text: "Chocolate Melter" },
          { text: "Coffee & Tea Maker" },
          { text: "Donut Maker" },
          { text: "Food & Drink Maker Lainnya" },
          { text: "Ice & Yogurt Maker" },
          { text: "Noodle & Pasta Maker" },
          { text: "Snack Maker" },
          { text: "Sushi Roller" },
          { text: "Toaster" },
          { text: "Waffle & Pancake Maker" },
        ],
      },
      {
        text: "Penyimpanan Makanan",
        sub: [
          { text: "Penyimpanan Makanan Lainnya" },
          { text: "Plastic Wrap" },
          { text: "Sealer" },
          { text: "Tempat Buah & Sayur" },
          { text: "Tempat Bumbu" },
          { text: "Tempat Roti" },
          { text: "Tempat Saos & Kecap" },
          { text: "Toples" },
        ],
      },
      {
        text: "Peralatan Dapur",
        sub: [
          { text: "Blender & Juicer" },
          { text: "Celemek" },
          { text: "Cetakan Es, Puding, Coklat" },
          { text: "Dispenser Minuman" },
          { text: "Gelas & Sendok Takar" },
          { text: "Kulkas & Cooler Box" },
          { text: "Magnet Kulkas" },
          { text: "Mixer" },
          { text: "Pelindung Tangan" },
          { text: "Pembuka Botol & Kaleng" },
          { text: "Peralatan Dapur Lainnya" },
          { text: "Perlengkapan Cuci Piring" },
          { text: "Pompa Galon" },
          { text: "Saringan" },
          { text: "Sarung Galon & Kulkas" },
          { text: "Timbangan Dapur" },
          { text: "Water Purifier" },
        ],
      },
      {
        text: "Peralatan Makan",
        sub: [
          { text: "Centong Nasi & Sendok Sayur" },
          { text: "Gelas & Mug" },
          { text: "Mangkok Makan" },
          { text: "Nampan" },
          { text: "Paket Peralatan Makan" },
          { text: "Paket Peralatan Minum" },
          { text: "Peralatan Makan Lainnya" },
          { text: "Piring & Mangkok Saji" },
          { text: "Piring Makan" },
          { text: "Pitcher" },
          { text: "Rak Piring & Tempat Gelas" },
          { text: "Sendok & Garpu" },
          { text: "Sumpit" },
          { text: "Tatakan Gelas & Piring" },
          { text: "Tempat Sendok & Garpu" },
          { text: "Tudung Saji" },
          { text: "Tutup Gelas & Piring" },
        ],
      },
      {
        text: "Peralatan Masak",
        sub: [
          { text: "Capit Makanan" },
          { text: "Griller" },
          { text: "Kompor" },
          { text: "Korek Kompor" },
          { text: "Microwave" },
          { text: "Oven" },
          { text: "Panci" },
          { text: "Peralatan Masak" },
          { text: "Presto" },
          { text: "Regulator & Penghemat Gas" },
          { text: "Rice Cooker" },
          { text: "Spatula & Sutil" },
          { text: "Steamer" },
          { text: "Teko & Pemanas Air" },
          { text: "Wajan" },
        ],
      },
      {
        text: "Pisau",
        sub: [
          { text: "Chopper" },
          { text: "Grinder" },
          { text: "Gunting Dapur" },
          { text: "Parutan" },
          { text: "Peeler" },
          { text: "Pengasah Pisau" },
          { text: "Pisau Dapur" },
          { text: "Pisau Lainnya" },
          { text: "Talenan" },
        ],
      },
    ],
  },
  {
    text: "Elektronik",
    sub: [
      {
        text: "Audio",
        sub: [
          { text: "Audio Lainnya" },
          { text: "Earphone" },
          { text: "Headphone" },
          { text: "Headset" },
          { text: "Speaker" },
        ],
      },
      {
        text: "Kamera Pengintai",
        sub: [
          { text: "Alarm" },
          { text: "DVR" },
          { text: "Fake Camera" },
          { text: "IP Camera" },
          { text: "Kamera CCTV" },
          { text: "Kamera Pengintai Lainnya" },
          { text: "Paket Perangkat Keamanan" },
          { text: "Spare Part" },
          { text: "Spy Camera" },
          { text: "Wireless Camera" },
        ],
      },
      {
        text: "Listrik",
        sub: [
          { text: "Alarm" },
          { text: "Anti Petir" },
          { text: "Bel" },
          { text: "Listrik Lainnya" },
          { text: "Pengaman Stop Kontak" },
          { text: "Penghemat Listrik" },
          { text: "Saklar" },
          { text: "Stop Kontak" },
        ],
      },
      {
        text: "Media Player",
        sub: [
          { text: "DVD Player" },
          { text: "MP3 Player" },
          { text: "MP4 Player" },
          { text: "Media Player Lainnya" },
          { text: "Receiver TV" },
        ],
      },
      {
        text: "Pencahayaan",
        sub: [
          { text: "Bohlam" },
          { text: "Lampu Baca" },
          { text: "Lampu Darurat" },
          { text: "Lampu Dinding" },
          { text: "Lampu Gantung" },
          { text: "Lampu Meja" },
          { text: "Lampu Proyektor" },
          { text: "Pencahayaan Lainnya" },
          { text: "Senter" },
        ],
      },
      {
        text: "Perangkat Elektronik Lainnya",
        sub: [
          { text: "Baterai" },
          { text: "GPS" },
          { text: "Kipas Angin Listrik" },
          { text: "Perangkat Elektronik Lainnya Lainnya" },
          { text: "Stun Gun" },
        ],
      },
      {
        text: "TV",
        sub: [
          { text: "Antena TV" },
          { text: "Bracket" },
          { text: "Kabel & Konektor" },
          { text: "LCD TV" },
          { text: "LED TV" },
          { text: "Plasma TV" },
          { text: "Remote TV" },
          { text: "TV Lainnya" },
        ],
      },
      {
        text: "Telepon",
        sub: [
          { text: "Mesin Fax" },
          { text: "Telepon Kabel" },
          { text: "Telepon Lainnya" },
          { text: "Telepon Satelit" },
          { text: "Telepon Wireless" },
        ],
      },
      {
        text: "Tool & Kit",
      },
      {
        text: "Vaporizer",
        sub: [
          { text: "Aksesoris Vape" },
          { text: "Atomizer" },
          { text: "Coil" },
          { text: "Kapas Vape" },
          { text: "Liquid" },
          { text: "MOD" },
        ],
      },
    ],
  },
  {
    text: "Fashion Anak",
    sub: [
      {
        text: "Aksesoris Anak",
        sub: [
          { text: "Dompet Anak" },
          { text: "Ikat Pinggang Anak" },
          { text: "Jam Tangan Anak" },
          { text: "Kacamata Anak" },
          { text: "Topi Anak" },
        ],
      },
      {
        text: "Aksesoris Rambut Anak",
        sub: [
          { text: "Bando" },
          { text: "Ikat Rambut" },
          { text: "Jepitan Rambut" },
        ],
      },
      {
        text: "Pakaian Anak Laki-Laki",
        sub: [
          { text: "Baju Setelan" },
          { text: "Baju Tidur Anak" },
          { text: "Celana Jeans" },
          { text: "Celana Panjang" },
          { text: "Celana Pendek" },
          { text: "Hoodies" },
          { text: "Jaket & Blazer" },
          { text: "Jumpsuits" },
          { text: "Kaos" },
          { text: "Kemeja" },
          { text: "Kostum" },
          { text: "Pakaian Anak Laki-Laki Lainnya" },
          { text: "Pakaian Dalam" },
          { text: "Seragam" },
        ],
      },
      {
        text: "Pakaian Anak Perempuan",
        sub: [
          { text: "Baby Dolls" },
          { text: "Baju Setelan" },
          { text: "Baju Tidur Anak Perempuan" },
          { text: "Blouse" },
          { text: "Bolero" },
          { text: "Bolero" },
          { text: "Cardigan" },
          { text: "Celana" },
          { text: "Celana Jeans" },
          { text: "Celana Pendek" },
          { text: "Dress" },
          { text: "Hoodies" },
          { text: "Jaket & Blazer" },
          { text: "Jumpsuits" },
          { text: "Kaos" },
          { text: "Kemeja" },
          { text: "Kostum" },
          { text: "Legging" },
          { text: "Pakaian Anak" },
          { text: "Pakaian Anak Perempuan Lainnya" },
          { text: "Pakaian Dalam" },
          { text: "Rok" },
          { text: "Seragam" },
          { text: "Tank Top" },
        ],
      },
      {
        text: "Perhiasan Anak",
        sub: [
          { text: "Anting" },
          { text: "Cincin" },
          { text: "Gelang" },
          { text: "Kalung" },
        ],
      },
      {
        text: "Sepatu Anak Laki-laki",
        sub: [
          { text: "Boots" },
          { text: "Kaos Kaki" },
          { text: "Sandal Jepit" },
          { text: "Sepatu Kets" },
          { text: "Sepatu Sandal" },
        ],
      },
      {
        text: "Sepatu Anak Perempuan",
        sub: [
          { text: "Boots" },
          { text: "Flat Shoes" },
          { text: "Kaos Kaki" },
          { text: "Sandal Jepit" },
          { text: "Sepatu Kets" },
          { text: "Sepatu Pesta" },
          { text: "Sepatu Sandal" },
        ],
      },
      {
        text: "Tas Anak",
        sub: [
          { text: "Tas Backpack Anak" },
          { text: "Tas Koper Anak" },
          { text: "Tas Selempang Anak" },
        ],
      },
    ],
  },
  {
    text: "Fashion Muslim",
    sub: [
      {
        text: "Aksesoris Jilbab",
        sub: [{ text: "Brooch" }, { text: "Headpiece" }],
      },
      {
        text: "Atasan",
        sub: [
          { text: "Baju Koko" },
          { text: "Blouse Muslim" },
          { text: "Kemeja Muslim" },
          { text: "Manset Muslim" },
        ],
      },
      {
        text: "Baju Muslim Anak",
      },
      {
        text: "Bawahan",
        sub: [
          { text: "Celana Muslim" },
          { text: "Legging" },
          { text: "Palazzo" },
          { text: "Rok Muslim" },
        ],
      },
      {
        text: "Dress",
        sub: [
          { text: "Abaya" },
          { text: "Gamis" },
          { text: "Jumpsuit" },
          { text: "Kaftan" },
        ],
      },
      {
        text: "Outerwear",
        sub: [
          { text: "Cape" },
          { text: "Cardigan" },
          { text: "Coat" },
          { text: "Vest" },
        ],
      },
      {
        text: "Perlengkapan Ibadah",
        sub: [
          { text: "Mukena" },
          { text: "Peci" },
          { text: "Sajadah" },
          { text: "Sarung" },
          { text: "Tasbih" },
        ],
      },
      {
        text: "Scarf",
        sub: [
          { text: "Ciput" },
          { text: "Hijab Instan" },
          { text: "Hijab Segi Empat" },
          { text: "Khimar" },
          { text: "Pashmina" },
        ],
      },
      {
        text: "Setelan Muslim",
      },
    ],
  },
  {
    text: "Fashion Pria",
    sub: [
      {
        text: "Aksesoris",
        sub: [
          { text: "Dasi" },
          { text: "Dompet Pria" },
          { text: "Ikat Pinggang Pria" },
          { text: "Kacamata" },
          { text: "Kacamata Hitam" },
          { text: "Sarung Tangan Fashion" },
          { text: "Topi Pria" },
        ],
      },
      {
        text: "Atasan",
        sub: [
          { text: "Kaos" },
          { text: "Kaos Tanpa Lengan" },
          { text: "Kemeja Casual" },
          { text: "Kemeja Formal" },
          { text: "Polo Shirt" },
        ],
      },
      {
        text: "Baju Tidur",
        sub: [{ text: "Celana Tidur" }, { text: "Piyama" }],
      },
      {
        text: "Batik Pria",
        sub: [{ text: "Celana" }, { text: "Kemeja" }],
      },
      {
        text: "Celana",
        sub: [{ text: "Jeans" }, { text: "Panjang" }, { text: "Pendek" }],
      },
      {
        text: "Jam Tangan",
        sub: [
          { text: "Analog" },
          { text: "Digital" },
          { text: "LED" },
          { text: "Strap" },
        ],
      },
      {
        text: "Outerwear",
        sub: [
          { text: "Cardigan" },
          { text: "Coat" },
          { text: "Hoodie" },
          { text: "Jaket" },
          { text: "Jas" },
          { text: "Sweater" },
          { text: "Vest" },
        ],
      },
      {
        text: "Pakaian Dalam Pria",
        sub: [
          { text: "Boxer" },
          { text: "Celana Dalam" },
          { text: "Kaos Dalam" },
        ],
      },
      {
        text: "Perhiasan Fashion",
        sub: [
          { text: "Anting" },
          { text: "Batu Mulia & Batu Alam" },
          { text: "Cincin" },
          { text: "Gelang" },
          { text: "Kalung" },
        ],
      },
      {
        text: "Sepatu",
        sub: [
          { text: "Boots" },
          { text: "Kaos Kaki" },
          { text: "Loafers" },
          { text: "Pantofel" },
          { text: "Perawatan Sepatu" },
          { text: "Sandal" },
          { text: "Sepatu Sandal" },
          { text: "Slip On" },
          { text: "Sneakers" },
        ],
      },
      {
        text: "Tas",
        sub: [
          { text: "Backpack" },
          { text: "Briefcase" },
          { text: "Clutch" },
          { text: "Tas Selempang" },
          { text: "Tas Travel" },
          { text: "Waist Bag" },
        ],
      },
    ],
  },
  {
    text: "Fashion Wanita",
    sub: [
      {
        text: "Aksesoris",
        sub: [
          { text: "Dompet Wanita" },
          { text: "Frame Kacamata" },
          { text: "Ikat Pinggang Wanita" },
          { text: "Kacamata" },
          { text: "Kacamata Hitam" },
          { text: "Sarung Tangan Fashion" },
          { text: "Scarf & Shawl" },
          { text: "Topi Wanita" },
        ],
      },
      {
        text: "Aksesoris Rambut",
        sub: [
          { text: "Bando" },
          { text: "Hair Extension" },
          { text: "Ikat Rambut" },
          { text: "Jepitan Rambut" },
          { text: "Mahkota & Headpiece" },
          { text: "Rambut Palsu" },
        ],
      },
      {
        text: "Atasan",
        sub: [
          { text: "Blouse" },
          { text: "Crop Top" },
          { text: "Kaos" },
          { text: "Kemeja" },
          { text: "Polo Shirt" },
          { text: "Tank Top" },
        ],
      },
      {
        text: "Baju Tidur",
        sub: [{ text: "Celana Tidur" }, { text: "Daster" }, { text: "Piyama" }],
      },
      {
        text: "Batik Wanita",
        sub: [
          { text: "Batik Couple" },
          { text: "Bawahan Batik" },
          { text: "Blouse Batik" },
          { text: "Dress Batik" },
          { text: "Kain Batik" },
          { text: "Kebaya" },
        ],
      },
      {
        text: "Celana",
        sub: [
          { text: "Celana Crop" },
          { text: "Celana Jeans" },
          { text: "Celana Panjang" },
          { text: "Celana Pendek" },
          { text: "Hot Pants" },
          { text: "Legging" },
        ],
      },
      {
        text: "Dress",
        sub: [
          { text: "Jumpsuit" },
          { text: "Maxi Dress" },
          { text: "Midi Dress" },
          { text: "Mini Dress" },
        ],
      },
      {
        text: "Jam Tangan",
        sub: [
          { text: "Jam Tangan Analog" },
          { text: "Jam Tangan Digital" },
          { text: "Jam Tangan LED" },
        ],
      },
      {
        text: "Outerwear",
        sub: [
          { text: "Blazer" },
          { text: "Cardigan" },
          { text: "Coat" },
          { text: "Hoodie" },
          { text: "Jaket" },
          { text: "Sweater" },
          { text: "Vest" },
        ],
      },
      {
        text: "Pakaian Dalam Wanita",
        sub: [
          { text: "BRA" },
          { text: "Celana Dalam" },
          { text: "G-String" },
          { text: "Korset" },
          { text: "Lingerie" },
        ],
      },
      {
        text: "Perhiasan",
        sub: [
          { text: "Anting" },
          { text: "Bros" },
          { text: "Cincin" },
          { text: "Gelang" },
          { text: "Kalung" },
          { text: "Liontin" },
          { text: "Logam Mulia" },
        ],
      },
      {
        text: "Perlengkapan Couple",
        sub: [
          { text: "Aksesoris Couple" },
          { text: "Baju Couple" },
          { text: "Cincin Couple" },
          { text: "Jam Tangan Couple" },
        ],
      },
      {
        text: "Perlengkapan Jahit",
        sub: [
          { text: "Alat Ukur Baju" },
          { text: "Benang" },
          { text: "Jarum Jahit" },
          { text: "Kancing" },
          { text: "Manekin" },
          { text: "Mesin Jahit" },
          { text: "Patch" },
          { text: "Payet" },
          { text: "Peniti" },
          { text: "Resleting" },
        ],
      },
      {
        text: "Rok",
        sub: [{ text: "Rok Maxi" }, { text: "Rok Midi" }, { text: "Rok Mini" }],
      },
      {
        text: "Sepatu",
        sub: [
          { text: "Boots" },
          { text: "Flat Shoes" },
          { text: "Heels" },
          { text: "Kaos Kaki" },
          { text: "Loafers" },
          { text: "Sandal" },
          { text: "Sepatu Sandal" },
          { text: "Slip On" },
          { text: "Sneakers" },
          { text: "Wedges" },
        ],
      },
      {
        text: "Setelan",
      },
      {
        text: "Tas",
        sub: [
          { text: "Aksesoris Tas" },
          { text: "Backpack" },
          { text: "Clutch" },
          { text: "Hand Bag" },
          { text: "Shoulder Bag" },
          { text: "Tas Kosmetik" },
          { text: "Tas Selempang" },
          { text: "Tote Bag" },
        ],
      },
    ],
  },
  {
    text: "Film & Musik",
    sub: [
      {
        text: "Movie & Serial TV",
      },
      {
        text: "Musik",
        sub: [
          { text: "Alat Musik" },
          { text: "CD & DVD Musik" },
          { text: "Musik Lainnya" },
        ],
      },
    ],
  },
  {
    text: "Gaming",
    sub: [
      {
        text: "CD Game",
        sub: [
          { text: "CD Nintendo" },
          { text: "CD PC dan Laptop Gaming" },
          { text: "CD PlayStation" },
          { text: "CD Xbox" },
        ],
      },
      {
        text: "Game Console",
        sub: [
          { text: "Aksesoris Game Console" },
          { text: "Game Boy dan Game Retro" },
          { text: "Joystick" },
          { text: "Komponen Game Console" },
          { text: "Memory Card" },
          { text: "Nintendo" },
          { text: "PlayStation" },
          { text: "Wheels" },
          { text: "Xbox" },
        ],
      },
      {
        text: "PC dan Laptop Gaming",
        sub: [
          { text: "Aksesoris PC Gaming" },
          { text: "Headset Gaming" },
          { text: "Keyboard Gaming" },
          { text: "Komponen Komputer" },
          { text: "Laptop Gaming" },
          { text: "Monitor" },
          { text: "Mouse & Keyboard Gaming Bundle" },
          { text: "Mouse Gaming" },
          { text: "PC Controller" },
          { text: "PC Gaming" },
          { text: "Virtual Reality Glasses" },
        ],
      },
    ],
  },
  {
    text: "Handphone & Tablet",
    sub: [
      {
        text: "Aksesoris Handphone",
        sub: [
          { text: "Aksesoris Handphone Lainnya" },
          { text: "Aksesoris Mobil" },
          { text: "Baterai" },
          { text: "Casing & Cover" },
          { text: "Charger" },
          { text: "Docking Handphone" },
          { text: "Gantungan Handphone" },
          { text: "Mount Handphone" },
          { text: "Screen Guard" },
          { text: "Skin Handphone" },
          { text: "Spare Part" },
        ],
      },
      {
        text: "Aksesoris Tablet",
        sub: [
          { text: "Aksesoris Mobil" },
          { text: "Aksesoris Tablet Lainnya" },
          { text: "Baterai" },
          { text: "Casing & Cover" },
          { text: "Charger" },
          { text: "Connection Kit" },
          { text: "Docking Handphone" },
          { text: "Keyboard Bluetooth" },
          { text: "Mount Tablet" },
          { text: "Screen Guard" },
          { text: "Spare Part" },
        ],
      },
      {
        text: "Handphone",
      },
      {
        text: "Headset Bluetooth",
      },
      {
        text: "Kabel & Konektor",
      },
      {
        text: "Kabel Data",
      },
      {
        text: "Lensa Handphone",
      },
      {
        text: "Memory Card",
        sub: [
          { text: "Compact Flash" },
          { text: "MMC" },
          { text: "Memory Card Lainnya" },
          { text: "Memory Stick Micro M2" },
          { text: "Memory Stick PRO Duo" },
          { text: "Memory Stick PRO-HG Duo" },
          { text: "SD Card" },
          { text: "microSD Card" },
          { text: "miniSD Card" },
        ],
      },
      {
        text: "Nomor Perdana & Voucher",
      },
      {
        text: "Pelindung Kabel",
      },
      {
        text: "Power Bank",
      },
      {
        text: "Smartwatch",
      },
      {
        text: "Stylus",
      },
      {
        text: "Tablet",
      },
      {
        text: "Tomsis",
      },
      {
        text: "Tongsis",
      },
      {
        text: "Virtual Reality Glasses",
      },
    ],
  },
  {
    text: "Ibu & Bayi",
    sub: [
      {
        text: "Aksesoris Bayi",
        sub: [
          { text: "Headband Bayi" },
          { text: "Perhiasan Bayi" },
          { text: "Topi Bayi" },
        ],
      },
      {
        text: "Alat Bantu Jalan Bayi",
      },
      {
        text: "Baju & Sepatu Bayi",
        sub: [
          { text: "Baju & Sepatu Bayi Lainnya" },
          { text: "Baju Bayi Laki-laki" },
          { text: "Baju Bayi Perempuan" },
          { text: "Jaket Bayi" },
          { text: "Jumper Bayi" },
          { text: "Pakaian Bayi Unisex" },
          { text: "Sarung Tangan & Kaos Kaki" },
          { text: "Sepatu" },
        ],
      },
      {
        text: "Baju Hamil",
        sub: [
          { text: "Apron Menyusui" },
          { text: "Baju Atasan Hamil" },
          { text: "Bra Menyusui" },
          { text: "Celana Dalam Hamil" },
          { text: "Celana Hamil" },
          { text: "Dress Hamil" },
          { text: "Gurita" },
          { text: "Korset Ibu Hamil" },
          { text: "Rok Hamil" },
        ],
      },
      {
        text: "Breast Pump",
      },
      {
        text: "Mainan Bayi",
        sub: [
          { text: "Mainan Edukasi" },
          { text: "Mainan Gigi" },
          { text: "Mainan Luar Ruang" },
          { text: "Playmat" },
          { text: "Bouncer" },
        ],
      },
      {
        text: "Makanan & Susu Bayi",
        sub: [
          { text: "Biskuit Bayi" },
          { text: "Bubur Bayi" },
          { text: "Makanan & Susu Bayi Lainnya" },
          { text: "Susu Bayi" },
        ],
      },
      {
        text: "Perawatan Bayi",
        sub: [
          { text: "Bedak Bayi" },
          { text: "Cream Bayi" },
          { text: "Kapas dan Tissue" },
          { text: "Kesehatan Bayi" },
          { text: "Minyak Telon" },
        ],
      },
      {
        text: "Perawatan Ibu",
        sub: [
          { text: "ASI Booster" },
          { text: "Nipple Cream" },
          { text: "Susu Ibu Hamil" },
          { text: "Vitamin & Nutrisi Ibu Hamil" },
        ],
      },
      {
        text: "Perlengkapan Makan Bayi",
        sub: [
          { text: "Baby Food Maker" },
          { text: "Botol Susu Sanitizer" },
          { text: "Celemek Bayi" },
          { text: "Dot" },
          { text: "Kursi Makan Bayi" },
          { text: "Set Peralatan Makan Bayi" },
        ],
      },
      {
        text: "Perlengkapan Mandi Bayi",
        sub: [
          { text: "Bathub dan Kolam" },
          { text: "Handuk dan Peralatan Mandi" },
          { text: "Mainan Mandi" },
          { text: "Pelampung" },
          { text: "Pispot" },
          { text: "Sabun Bayi" },
          { text: "Shampoo Bayi" },
          { text: "Topi Pelindung Air" },
        ],
      },
      {
        text: "Perlengkapan Tidur Bayi",
        sub: [
          { text: "Baby Monitor" },
          { text: "Bantal dan Guling" },
          { text: "Kelambu" },
          { text: "Selimut dan Bedong" },
          { text: "Tempat Tidur Bayi" },
        ],
      },
      {
        text: "Popok dan Diaper",
        sub: [{ text: "Diaper" }, { text: "Popok Kain" }],
      },
      {
        text: "Stroller dan Alat Bantu Bawa Bayi",
        sub: [
          { text: "Dudukan Mobil Bayi" },
          { text: "Gendongan Bayi" },
          { text: "Stroller" },
        ],
      },
      {
        text: "Tas Perlengkapan Bayi",
      },
    ],
  },
  {
    text: "Kamera",
    sub: [
      {
        text: "Aksesoris Kamera",
        sub: [
          { text: "Aksesoris Kamera Lainnya" },
          { text: "Kabel Konektor" },
          { text: "Lighting & Studio" },
          { text: "Memory Card Kamera" },
          { text: "Remote - Wireless" },
          { text: "Strap Kamera" },
          { text: "Tas & Casing Kamera" },
          { text: "Tripod & Stabillizer" },
          { text: "Waterproof Case" },
        ],
      },
      {
        text: "Baterai, Charger & Grip",
        sub: [
          { text: "Baterai" },
          { text: "Baterai, Charger & Grip Lainnya" },
          { text: "Battery Grip" },
          { text: "Charger" },
        ],
      },
      {
        text: "Cleaner & Tool Kit",
        sub: [
          { text: "Blower" },
          { text: "Cleaner & Tool Kit Lainnya" },
          { text: "Cleaning Cloth" },
          { text: "Cleaning Kit" },
          { text: "Dry Box" },
          { text: "Lenspen" },
          { text: "Silica Gel" },
        ],
      },
      {
        text: "Flash & Aksesoris",
        sub: [
          { text: "Diffuser" },
          { text: "Flash" },
          { text: "Flash & Aksesoris Lainnya" },
          { text: "Flash Trigger" },
          { text: "Hot Shoe" },
        ],
      },
      {
        text: "Frame, Album & Roll Film",
        sub: [
          { text: "Album" },
          { text: "DVs" },
          { text: "Frame Digital" },
          { text: "Frame Foto" },
          { text: "Roll Film" },
        ],
      },
      {
        text: "Kamera Analog",
        sub: [
          { text: "Kamera Analog Lainnya" },
          { text: "Kamera Instan" },
          { text: "Lomo" },
        ],
      },
      {
        text: "Kamera Digital",
        sub: [
          { text: "Action Camera" },
          { text: "Kamera DSLR" },
          { text: "Kamera Digital" },
          { text: "Kamera Mirrorless" },
          { text: "Kamera Pocket - Prosumer" },
        ],
      },
      {
        text: "Kamera Video",
        sub: [
          { text: "Camcorder" },
          { text: "Drone" },
          { text: "Kamera Video" },
        ],
      },
      {
        text: "Lensa & Aksesoris",
        sub: [
          { text: "Adapter" },
          { text: "Cap" },
          { text: "Converter - Teleconverter" },
          { text: "Filter" },
          { text: "Hood" },
          { text: "Lensa" },
          { text: "Lensa & Aksesoris Lainnya" },
        ],
      },
    ],
  },
  {
    text: "Kecantikan",
    sub: [
      {
        text: "Aksesoris & Alat Make Up",
        sub: [
          { text: "Beauty Sponge" },
          { text: "Cermin Make Up" },
          { text: "Kemasan Make Up" },
          { text: "Laci & Tempat Makeup" },
          { text: "Pembersih Brush Make Up" },
          { text: "Pinset Komedo" },
          { text: "Set Makeup Brush" },
          { text: "Tas Kosmetik" },
        ],
      },
      {
        text: "Eyebrow Kit",
        sub: [
          { text: "Cetakan dan Sisir Alis" },
          { text: "Eyebrow Powder & Pomade" },
          { text: "Pensil Alis" },
          { text: "Pinset dan Cukuran Alis" },
        ],
      },
      {
        text: "Hand & Nail Art",
        sub: [
          { text: "Alat & Aksesoris Nail art" },
          { text: "Fake Nail" },
          { text: "Henna" },
          { text: "Kutek" },
          { text: "Lem Kuku Palsu" },
          { text: "Portable Nail Dryer" },
          { text: "Stiker Kuku" },
        ],
      },
      {
        text: "Lip Color & Lip Care",
        sub: [
          { text: "Lip Balm & Oil" },
          { text: "Lip Cream" },
          { text: "Lip Scrub" },
          { text: "Lip Tint" },
          { text: "LipglossLi" },
          { text: "Lipstik dan Pensil Bibir" },
        ],
      },
      {
        text: "Make Up Mata",
        sub: [
          { text: "Bulu Mata Palsu" },
          { text: "Eye Liner" },
          { text: "Eye Primer" },
          { text: "Eyelid Tape" },
          { text: "Eyeshadow" },
          { text: "Lem Bulu Mata" },
          { text: "Mascara" },
          { text: "Pinset & Penjepit Bulu Mata" },
        ],
      },
      {
        text: "Make Up Wajah",
        sub: [
          { text: "BB cream & CC cream, BB cushion" },
          { text: "Bedak Wajah" },
          { text: "Blush on" },
          { text: "Bronzer & Highlighter" },
          { text: "Concealer" },
          { text: "Face primer" },
          { text: "Foundation" },
          { text: "Setting Spray" },
        ],
      },
      {
        text: "Perawatan Kulit",
        sub: [
          { text: "Anti Selulit & Stretchmark" },
          { text: "Penghilang Bekas Jerawat" },
          { text: "Penghilang Bekas Luka" },
        ],
      },
      {
        text: "Perawatan Wajah",
        sub: [
          { text: "Cleanser" },
          { text: "Krim Mata" },
          { text: "Krim Wajah" },
          { text: "Masker Bibir" },
          { text: "Masker Wajah" },
          { text: "Paket Perawatan Wajah" },
          { text: "Pembersih Make Up" },
          { text: "Scrub & Peeling Wajah" },
          { text: "Serum & Masker Mata" },
          { text: "Serum & Minyak Wajah" },
          { text: "Skin Care Tools" },
          { text: "Sunblock Wajah" },
          { text: "Toner" },
        ],
      },
      {
        text: "Set & Palette Makeup",
      },
      {
        text: "Styling Rambut Wanita",
        sub: [
          { text: "Aksesoris Rambut" },
          { text: "Alat Potong Rambut" },
          { text: "Catokan" },
          { text: "Hair Dryer" },
          { text: "Hair Extension" },
          { text: "Produk Styling Rambut" },
          { text: "Rambut Palsu" },
          { text: "Sisir" },
        ],
      },
    ],
  },
  {
    text: "Kesehatan",
    sub: [
      {
        text: "Alat Bantu Kesehatan",
        sub: [
          { text: "Alat Bantu Pendengaran" },
          { text: "Alat Pelangsing" },
          { text: "Alat Pijat" },
          { text: "Behel" },
          { text: "Earmuff" },
          { text: "Kacamata Terapi" },
          { text: "Peralatan P3K" },
          { text: "Termometer" },
          { text: "Timbangan Badan" },
        ],
      },
      {
        text: "Diet & Vitamin",
        sub: [
          { text: "Detox" },
          { text: "Diet & Vitamin Lainnya" },
          { text: "Obat Pelangsing" },
          { text: "Penambah Berat Badan" },
          { text: "Suplemen Fitness" },
          { text: "Vitamin & Nutrisi" },
          { text: "Vitamin Daya Tahan Tubuh" },
        ],
      },
      {
        text: "Essential Oil",
      },
      {
        text: "Kesehatan Lainnya",
      },
      {
        text: "Kesehatan Wanita",
        sub: [
          { text: "Alat Kontrasepsi" },
          { text: "Kesehatan Wanita Lainnya" },
          { text: "Obat Menopause" },
          { text: "Obat Menstruasi" },
          { text: "Perawatan Tubuh Wanita" },
          { text: "Produk Kesehatan Wanita" },
        ],
      },
      {
        text: "Maternity",
        sub: [
          { text: "Asi Booster" },
          { text: "Kehamilan" },
          { text: "Nipple Cream" },
          { text: "Susu Hamil" },
          { text: "Vitamin Ibu Hamil" },
        ],
      },
      {
        text: "Obat - Obatan",
        sub: [
          { text: "Koyo" },
          { text: "Obat Batuk dan Pilek" },
          { text: "Obat Diabetes" },
          { text: "Obat Generik" },
          { text: "Obat Herbal" },
          { text: "Obat Jerawat" },
          { text: "Obat Lainnya" },
          { text: "Obat Pencernaan" },
          { text: "Obat Penumbuh Rambut" },
          { text: "Obat Sakit Kepala dan Demam" },
          { text: "Salep" },
        ],
      },
      {
        text: "Perlengkapan Medis",
        sub: [
          { text: "Alat Bantu Jalan" },
          { text: "Alat Diagnosa" },
          { text: "Alat Laboratorium" },
          { text: "Alat Lainnya" },
          { text: "Alat Monitor Kesehatan" },
          { text: "Alat Terapi" },
        ],
      },
    ],
  },
  {
    text: "Komputer & Aksesoris",
    sub: [
      {
        text: "Desktop & Mini PC",
      },
      {
        text: "Harddisk & Flashdisk",
        sub: [
          { text: "Flash Disk" },
          { text: "HDD Cases & Docking" },
          { text: "HDD External" },
          { text: "HDD Internal" },
          { text: "SSD" },
        ],
      },
      {
        text: "Komponen Komputer",
        sub: [
          { text: "CPU Cooler" },
          { text: "Casing Komputer" },
          { text: "Fan Case" },
          { text: "Harddisk Cooler" },
          { text: "Memory" },
          { text: "Memory Cooler" },
          { text: "Monitor" },
          { text: "Motherboard AMD" },
          { text: "Motherboard Intel" },
          { text: "Power Supply Unit (PSU)" },
          { text: "Processor AMD" },
          { text: "Processor Intel" },
          { text: "Sound Card" },
          { text: "Stabilizer" },
          { text: "Thermal Paste" },
          { text: "UPS" },
          { text: "VGA Cooler" },
        ],
      },
      {
        text: "Networking",
        sub: [
          { text: "Antena Penguat Sinyal" },
          { text: "KVM Switch" },
          { text: "Kabel & Konektor" },
          { text: "Modem USB" },
          { text: "Network Card" },
          { text: "Network Transceiver" },
          { text: "Networking Lainnya" },
          { text: "Power Over Ethernet" },
          { text: "Powerline" },
          { text: "Print Server" },
          { text: "Switch Internet" },
          { text: "Wired Router" },
          { text: "Wireless Adapter" },
          { text: "Wireless Router" },
        ],
      },
      {
        text: "Optical Drive",
        sub: [
          { text: "Blu-ray" },
          { text: "CD" },
          { text: "DVD" },
          { text: "Duplicator" },
        ],
      },
      {
        text: "Peripheral & Aksesoris",
        sub: [
          { text: "CD & DVD Kosong" },
          { text: "Card Readers" },
          { text: "Joystick & Wheel" },
          { text: "Kabel & Konektor" },
          { text: "Keyboard" },
          { text: "Keypad" },
          { text: "Mouse" },
          { text: "Mouse & Keyboard Bundle" },
          { text: "Mousepad" },
          { text: "Peripheral & Aksesoris Lainnya" },
          { text: "Proyektor & Perangkat Presentasi" },
          { text: "Scanner" },
          { text: "TV Card & Tuner" },
          { text: "Tools & Kits" },
          { text: "USB Hub" },
          { text: "Webcam" },
        ],
      },
      {
        text: "Printer",
        sub: [
          { text: "All in One" },
          { text: "Barcode" },
          { text: "Dot Matrix" },
          { text: "Ink Jet" },
          { text: "Kertas Printer" },
          { text: "Laser Color" },
          { text: "Laser Mono" },
          { text: "Point of Sales (POS)" },
          { text: "Printer Lainnya" },
          { text: "Spare Part" },
          { text: "Tinta Printer" },
        ],
      },
      {
        text: "VGA Card",
        sub: [
          { text: "AGP Series" },
          { text: "AMD Series - ATI" },
          { text: "NVIDIA Series - Geforce" },
        ],
      },
    ],
  },
  {
    text: "Laptop & Aksesoris",
    sub: [
      {
        text: "Aksesoris Laptop",
        sub: [
          { text: "Adaptor Laptop" },
          { text: "Aksesoris Laptop Lainnya" },
          { text: "Baterai Laptop" },
          { text: "Cooling Pad" },
          { text: "Meja Laptop" },
          { text: "Memory RAM" },
          { text: "Protector" },
          { text: "Skin Laptop" },
          { text: "Spare Part Laptop" },
          { text: "Tas Laptop" },
        ],
      },
      {
        text: "Laptop",
      },
    ],
  },
  {
    text: "Mainan & Hobi",
    sub: [
      {
        text: "Diecast",
        sub: [
          { text: "Bangunan & Track Diecast" },
          { text: "Diecast Bus" },
          { text: "Diecast Kapal" },
          { text: "Diecast Kendaraan Publik" },
          { text: "Diecast Lainnya" },
          { text: "Diecast Militer" },
          { text: "Diecast Mobil" },
          { text: "Diecast Motor & Sepeda" },
          { text: "Diecast Pesawat" },
          { text: "Diecast Set" },
          { text: "Diecast Truk & Konstruksi" },
        ],
      },
      {
        text: "Figure",
        sub: [
          { text: "Action Figure" },
          { text: "Figure Lainnya" },
          { text: "Super Deformed Figure" },
        ],
      },
      {
        text: "Mainan & Hobi Lainnya",
        sub: [
          { text: "Alat Berkebun & Hewan Peliharaan" },
          { text: "Board Game" },
          { text: "Gag & Prank Toy" },
          { text: "Kartu" },
          { text: "Lainnya Lainnya" },
          { text: "Miniatur" },
          { text: "Peralatan Camping & Olahraga Outdoor" },
          { text: "Puzzle" },
          { text: "Sulap" },
        ],
      },
      {
        text: "Mainan Anak",
        sub: [{ text: "" }],
      },
      {
        text: "Mainan Remote Control",
        sub: [
          { text: "Helikopter RC" },
          { text: "Kapal RC" },
          { text: "Mainan Remote Control Lainnya" },
          { text: "Mobil & Truk RC" },
          { text: "Part RC" },
          { text: "Pesawat RC" },
        ],
      },
      {
        text: "Model Kit",
        sub: [
          { text: "Brick (Lego)" },
          { text: "Mecha Model (Gunpla)" },
          { text: "Model Kit Lainnya" },
          { text: "Part Mini 4WD (Tamiya)" },
          { text: "Tool & Kit Mecha Model (Gunpla)" },
          { text: "Vehicle Model (Tamiya)" },
        ],
      },
    ],
  },
  {
    text: "Makanan & Minuman",
    sub: [
      {
        text: "Biskuit & Kue",
        sub: [
          { text: "Biskuit & Kue Lainnya" },
          { text: "Biskuit Krakers" },
          { text: "Kue" },
          { text: "Kue Kering" },
          { text: "Rolls" },
          { text: "Wafer" },
        ],
      },
      {
        text: "Bumbu & Bahan Dasar",
        sub: [
          { text: "Bumbu & Bahan Dasar Lainnya" },
          { text: "Kaldu" },
          { text: "Minyak" },
          { text: "Salt & Spices" },
          { text: "Sambal" },
          { text: "Saus & Bumbu" },
          { text: "Tepung" },
        ],
      },
      {
        text: "Makanan & Minuman Kesehatan",
        sub: [
          { text: "Madu" },
          { text: "Makanan & Minuman Kesehatan Lainnya" },
          { text: "Makanan Diet" },
          { text: "Minuman Kesehatan" },
          { text: "Susu Nutrisi" },
        ],
      },
      {
        text: "Makanan & Minuman Lainnya",
      },
      {
        text: "Makanan Beku",
        sub: [
          { text: "Buah" },
          { text: "Daging" },
          { text: "Daging Olahan" },
          { text: "Dessert" },
        ],
      },
      {
        text: "Makanan Kering",
        sub: [
          { text: "Camilan Tradisional" },
          { text: "Daging Kering & Asin" },
          { text: "Keripik" },
          { text: "Makanan Kering Lainnya" },
          { text: "Makanan Ringan" },
          { text: "Mie & Pasta" },
          { text: "Olahan Kacang" },
          { text: "Sereal" },
        ],
      },
      {
        text: "Makanan Manis",
        sub: [
          { text: "Buah-buahan" },
          { text: "Cokelat" },
          { text: "Makanan Manis Lainnya" },
          { text: "Permen" },
          { text: "Selai" },
        ],
      },
      {
        text: "Makanan Siap Saji",
        sub: [
          { text: "Daging Olahan" },
          { text: "Makanan Siap Saji Lainnya" },
          { text: "Modern Snack" },
          { text: "Seafood Kering" },
        ],
      },
      {
        text: "Minuman",
        sub: [
          { text: "Kopi" },
          { text: "Krimer & Gula" },
          { text: "Minuman Kaleng Cup" },
          { text: "Minuman Lainnya" },
          { text: "Minuman Rasa" },
          { text: "Susu" },
          { text: "Teh" },
        ],
      },
    ],
  },
  {
    text: "Office & Stationery",
    sub: [
      {
        text: "Alat Kesenian",
        sub: [
          { text: "Alat Kesenian Lainnya" },
          { text: "Art Set" },
          { text: "Buku Gambar & Sketsa" },
          { text: "Cat Air" },
          { text: "Cat Akrilik" },
          { text: "Cat Minyak" },
          { text: "Cat Poster" },
          { text: "Crayon" },
          { text: "Kanvas Lukis" },
          { text: "Kuas Lukis" },
          { text: "Oil & Dry Pastel" },
          { text: "Palet" },
          { text: "Pensil Warna" },
          { text: "Spidol Warna" },
        ],
      },
      {
        text: "Alat Pemotong Kertas",
        sub: [
          { text: "Alat Pemotong Kertas Lainnya" },
          { text: "Art Knife" },
          { text: "Cutter" },
          { text: "Cutting Mat" },
          { text: "Gunting" },
        ],
      },
      {
        text: "Alat Tulis",
        sub: [
          { text: "Alat Tulis Lainnya" },
          { text: "Correction (Tip-X)" },
          { text: "Highlighter" },
          { text: "Paket Alat Tulis" },
          { text: "Papan Tulis & Tempel" },
          { text: "Penggaris" },
          { text: "Penghapus" },
          { text: "Pensil" },
          { text: "Pulpen" },
          { text: "Rautan" },
          { text: "Spidol Papan Tulis" },
          { text: "Stationery Stand" },
          { text: "Tempat Pensil" },
          { text: "Tinta" },
        ],
      },
      {
        text: "Document & Desk Organizer",
        sub: [
          { text: "Binder" },
          { text: "Box File" },
          { text: "Card Holder" },
          { text: "Document & Desk Organizer Lainnya" },
          { text: "Map" },
          { text: "Ordner" },
          { text: "Passport Cover" },
        ],
      },
      {
        text: "Kalkulator & Kamus Elektronik",
        sub: [{ text: "Kalkulator" }, { text: "Kamus Elektronik" }],
      },
      {
        text: "Kertas",
        sub: [
          { text: "Buku Catatan" },
          { text: "Buku Keuangan" },
          { text: "Buku Telepon & Alamat" },
          { text: "Buku Tulis" },
          { text: "Kertas Fax" },
          { text: "Kertas File" },
          { text: "Kertas Lainnya" },
          { text: "Kertas Print & Fotocopy" },
          { text: "Memo & Sticky Notes" },
          { text: "Pembatas Buku" },
          { text: "Pembolong Kertas" },
          { text: "Penghancur Kertas" },
          { text: "Sampul Buku" },
        ],
      },
      {
        text: "Office & Stationery Lainnya",
      },
      {
        text: "Pengikat & Perekat",
        sub: [
          { text: "Klip Kabel" },
          { text: "Klip Kertas" },
          { text: "Lem Kertas" },
          { text: "Pengikat & Perekat Lainnya" },
          { text: "Selotip & Double Tape" },
          { text: "Staples" },
          { text: "Stiker" },
        ],
      },
      {
        text: "Surat-Menyurat",
        sub: [
          { text: "Amplop" },
          { text: "Kartu Pos" },
          { text: "Kertas Surat" },
          { text: "Perangko" },
          { text: "Stempel" },
          { text: "Surat-Menyurat Lainnya" },
        ],
      },
    ],
  },

  {
    text: "Olahraga",
    sub: [
      {
        text: "Airsoft Gun",
        sub: [
          { text: "Airsoft Gun Lainnya" },
          { text: "Baju & Rompi Airsoft" },
          { text: "Baterai & Gas Airsoft" },
          { text: "Goggle & Kacamata" },
          { text: "Helm & Topi Airsoft" },
          { text: "Holster, Case & Tas" },
          { text: "Pad & Glove Airsoft" },
          { text: "Scope" },
          { text: "Sepatu Airsoft" },
          { text: "Topeng & Balaclava" },
        ],
      },
      {
        text: "Aksesoris Olahraga",
        sub: [
          { text: "Aksesoris Olahraga Lainnya" },
          { text: "Bracer" },
          { text: "Headband" },
          { text: "Stopwatch" },
          { text: "Tas Olahraga" },
          { text: "Wristband" },
        ],
      },
      {
        text: "Alat Pancing",
        sub: [
          { text: "Alat Pancing Lainnya" },
          { text: "Fish Finder" },
          { text: "Fishing Reel" },
          { text: "Joran Pancing" },
          { text: "Kail Pancing" },
          { text: "Senar Pancing" },
          { text: "Set Alat Pancing" },
          { text: "Tas Pancing" },
          { text: "Umpan Pancing" },
        ],
      },
      {
        text: "Badminton",
        sub: [
          { text: "Badminton Lainnya" },
          { text: "Raket Badminton" },
          { text: "Sepatu Badminton" },
          { text: "Shuttlecock" },
        ],
      },
      {
        text: "Basket",
        sub: [
          { text: "Baju Basket" },
          { text: "Basket Lainnya" },
          { text: "Bola Basket" },
          { text: "Ring Basket" },
          { text: "Sepatu Basket" },
        ],
      },
      {
        text: "Beladiri",
        sub: [
          { text: "Baton" },
          { text: "Beladiri Lainnya" },
          { text: "Knuckle" },
          { text: "Nunchaku" },
        ],
      },
      {
        text: "Gym & Fitness",
        sub: [
          { text: "Alat Fitness" },
          { text: "Baju Olahraga Pria" },
          { text: "Baju Olahraga Wanita" },
          { text: "Celana Olahraga Pria" },
          { text: "Celana Olahraga Wanita" },
          { text: "Gym & Fitness Lainnya" },
          { text: "Sepatu Olahraga" },
          { text: "Setelan Olahraga Pria" },
          { text: "Setelan Olahraga Wanita" },
        ],
      },
      {
        text: "Olahraga Lainnya",
      },
      {
        text: "Outdoor Sport",
        sub: [
          { text: "Alat Masak Camping" },
          { text: "Carabiner" },
          { text: "Celana Gunung" },
          { text: "Headlamp" },
          { text: "Jaket Gunung" },
          { text: "Kompas" },
          { text: "Lampu Camping" },
          { text: "Outdoor Sport Lainnya" },
          { text: "Perahu Karet" },
          { text: "Senter Camping" },
          { text: "Sepatu Gunung" },
          { text: "Setelan Pakaian Gunung" },
          { text: "Sleeping Bag" },
          { text: "Survival Kit" },
          { text: "Tas Gunung" },
          { text: "Tenda" },
          { text: "Teropong" },
          { text: "Trekking Pole" },
          { text: "Walkie-talkie" },
        ],
      },
      {
        text: "Panahan",
        sub: [
          { text: "Akesoris Panahan" },
          { text: "Busur" },
          { text: "Panah" },
          { text: "Panahan Lainnya" },
        ],
      },
      {
        text: "Renang & Diving",
        sub: [
          { text: "Aksesoris Diving" },
          { text: "Alat Scuba" },
          { text: "Alat Snorkeling" },
          { text: "Baju Renang Anak Cewek" },
          { text: "Baju Renang Anak Cowok" },
          { text: "Baju Renang Wanita" },
          { text: "Celana Renang Pria" },
          { text: "Diving Fin" },
          { text: "Diving Mask" },
          { text: "Kacamata Renang" },
          { text: "Kolam Karet" },
          { text: "Pelampung" },
          { text: "Renang & Diving Lainnya" },
          { text: "Senter Diving" },
          { text: "Topi Renang" },
          { text: "Wetsuit & Drysuit" },
        ],
      },
      {
        text: "Sepak Bola & Futsal",
        sub: [
          { text: "Bola" },
          { text: "Jaket Bola" },
          { text: "Jersey Bola" },
          { text: "Kaos Kaki" },
          { text: "Sepak Bola & Futsal Lainnya" },
          { text: "Sepatu Bola" },
          { text: "Sepatu Futsal" },
        ],
      },
      {
        text: "Sepeda",
        sub: [
          { text: "Frame Sepeda" },
          { text: "Helm Sepeda" },
          { text: "Jersey & Celana Sepeda" },
          { text: "Lampu Sepeda" },
          { text: "Sarung Tangan Sepeda" },
          { text: "Sepeda" },
          { text: "Sepeda Lainnya" },
          { text: "Spare Part & Aksesoris Sepeda" },
        ],
      },
      {
        text: "Tenis",
        sub: [
          { text: "Bola Tenis" },
          { text: "Raket Tenis" },
          { text: "Sepatu Tenis" },
          { text: "Tenis Lainnya" },
        ],
      },
    ],
  },
  {
    text: "Otomotif",
    sub: [
      {
        text: "Aksesoris Mobil",
        sub: [
          { text: "Aksesoris Mobil Lainnya" },
          { text: "Audio Mobil" },
          { text: "Cover Mobil" },
          { text: "Eksterior" },
          { text: "Interior" },
          { text: "Klakson" },
          { text: "Knalpot" },
          { text: "Lampu" },
          { text: "Parfum Mobil" },
          { text: "Wheels" },
        ],
      },
      {
        text: "Aksesoris Motor",
        sub: [
          { text: "Aksesori Body" },
          { text: "Aksesoris Motor Lainnya" },
          { text: "Alarm & Gembok Motor" },
          { text: "Ban dan Velg" },
          { text: "Baut-baut" },
          { text: "Box Motor" },
          { text: "Footstep" },
          { text: "Handle - Handfat" },
          { text: "Jok Motor" },
          { text: "Klakson" },
          { text: "Knalpot" },
          { text: "Lampu" },
          { text: "Shockbreaker" },
          { text: "Spion" },
        ],
      },
      {
        text: "Aksesoris Pengendara Motor",
        sub: [
          { text: "Aksesoris" },
          { text: "Aksesoris Pengendara Motor Lainnya" },
          { text: "Jaket" },
          { text: "Jas Hujan" },
          { text: "Masker Motor" },
          { text: "Rompi" },
          { text: "Sarung Tangan" },
          { text: "Sepatu" },
        ],
      },
      {
        text: "Helm Motor",
        sub: [
          { text: "Full Face" },
          { text: "Half Face" },
          { text: "Helm Motor Lainnya" },
          { text: "Kaca Helm" },
          { text: "Kunci Helm" },
          { text: "Tas & Jaring Helm" },
        ],
      },
      {
        text: "Mobil",
      },
      {
        text: "Oli & Penghemat BBM",
        sub: [
          { text: "Octane Booster" },
          { text: "Oli & Penghemat BBM Lainnya" },
          { text: "Oli Mobil" },
          { text: "Oli Motor" },
          { text: "Penghemat BBM" },
        ],
      },
      {
        text: "Perawatan Kendaraan",
        sub: [
          { text: "Anti Ban Bocor" },
          { text: "Lap Chamois" },
          { text: "Pelumas Rantai" },
          { text: "Perawatan Kendaraan Lainnya" },
          { text: "Semir Ban" },
          { text: "Wash and Wax" },
        ],
      },
      {
        text: "Sepeda Motor",
      },
      {
        text: "Spare Part Mobil",
        sub: [
          { text: "Bearing" },
          { text: "Belt" },
          { text: "Busi" },
          { text: "Filter Udara" },
          { text: "Gearbox" },
          { text: "Kampas Rem" },
          { text: "Kopling" },
          { text: "Piston" },
          { text: "Radiator & Komponen" },
          { text: "Shockbreaker" },
          { text: "Spare Part Mobil Lainnya" },
        ],
      },
      {
        text: "Spare Part Motor",
        sub: [
          { text: "Aki Motor" },
          { text: "Bearing" },
          { text: "Busi" },
          { text: "CDI - ECU" },
          { text: "Filter Udara" },
          { text: "Kabel Selang" },
          { text: "Kaliper, Cakram dan Tromol" },
          { text: "Kampas Rem" },
          { text: "Karburator" },
          { text: "Koil" },
          { text: "Kopling" },
          { text: "Noken As" },
          { text: "Piston" },
          { text: "Rantai & Gir" },
          { text: "Spare Part Motor Lainnya" },
          { text: "V-Belt" },
        ],
      },
    ],
  },
  {
    text: "Perawatan Tubuh",
    sub: [
      {
        text: "Grooming",
        sub: [
          { text: "Alat & Krim Cukur" },
          { text: "Hair Foam" },
          { text: "Hair Wax & Pomade" },
          { text: "Sisir Saku" },
        ],
      },
      {
        text: "Kesehatan Gigi & Mulut",
        sub: [
          { text: "Benang Gigi & Tusuk Gigi" },
          { text: "Obat Kumur" },
          { text: "Pasta Gigi" },
          { text: "Pembersih Lidah" },
          { text: "Pemutih Gigi" },
          { text: "Sikat Gigi" },
        ],
      },
      {
        text: "Mandi & Perawatan Tubuh",
        sub: [
          { text: "Body Butter" },
          { text: "Body Lotion" },
          { text: "Body Scrub" },
          { text: "Deodorant" },
          { text: "Paket Perawatan & Perlengkapan Mandi" },
          { text: "Pemutih Ketiak" },
          { text: "Perontok Bulu" },
          { text: "Sabun Badan" },
          { text: "Sunblock Badan" },
        ],
      },
      {
        text: "Parfum, Cologne, & Fragrance",
        sub: [
          { text: "Parfum & Cologne Anak-Anak" },
          { text: "Parfum & Cologne Pria" },
          { text: "Parfum & Cologne Unisex" },
          { text: "Parfum & Cologne Wanita" },
        ],
      },
      {
        text: "Perawatan Kaki, Tangan & Kuku",
        sub: [
          { text: "Alat Manikur & Pedikur" },
          { text: "Gunting Kuku" },
          { text: "Hand Cream" },
          { text: "Hand Sanitizer" },
          { text: "Minyak Kutikula Kuku" },
          { text: "Paket Perawatan Tangan & Kaki" },
          { text: "Penghilang Cat Kuku" },
          { text: "Perawatan Kaki" },
          { text: "Sabun Cuci Tangan" },
        ],
      },
      {
        text: "Perawatan Mata",
        sub: [
          { text: "Cairan Pembersih Sofltens" },
          { text: "Softlens" },
          { text: "Tetes Mata" },
        ],
      },
      {
        text: "Perawatan Rambut",
        sub: [
          { text: "Conditioner" },
          { text: "Dry Shampoo" },
          { text: "Hair tonic" },
          { text: "Masker Rambut" },
          { text: "Minyak & Serum Rambut" },
          { text: "Pewarna Rambut" },
          { text: "Shampoo" },
        ],
      },
      {
        text: "Produk Kewanitaan",
        sub: [
          { text: "Pembalut" },
          { text: "Sabun Kewanitaan" },
          { text: "Tampon" },
        ],
      },
      {
        text: "Telinga",
        sub: [{ text: "Ear Candle" }, { text: "Pembersih Telinga" }],
      },
    ],
  },
  {
    text: "Produk Lainnya",
  },
  {
    text: "Rumah Tangga",
    sub: [
      {
        text: "Alat Pertukangan",
        sub: [
          { text: "Alat Pertukangan Lainnya" },
          { text: "Blow Torch" },
          { text: "Bor" },
          { text: "Gembok" },
          { text: "Gergaji" },
          { text: "Kunci Inggris" },
          { text: "Kunci L" },
          { text: "Lem Material" },
          { text: "Meteran" },
          { text: "Obeng" },
          { text: "Palu" },
          { text: "Pompa Angin" },
          { text: "Tang" },
          { text: "Tool Box" },
        ],
      },
      {
        text: "Dekorasi",
        sub: [
          { text: "Bunga Artificial" },
          { text: "Dekorasi Lainnya" },
          { text: "Gorden" },
          { text: "Jam Dinding" },
          { text: "Jam Meja" },
          { text: "Karpet & Tikar" },
          { text: "Keset" },
          { text: "Lilin" },
          { text: "Lukisan" },
          { text: "Patung" },
          { text: "Taplak Meja" },
          { text: "Tempat Lilin" },
          { text: "Vas Bunga" },
          { text: "Wall Sticker" },
          { text: "Wallpaper" },
        ],
      },
      {
        text: "Furniture",
        sub: [
          { text: "Furniture Lainnya" },
          { text: "Kursi & Sofa" },
          { text: "Lemari" },
          { text: "Meja" },
          { text: "Pengaman Furniture" },
          { text: "Rak" },
        ],
      },
      {
        text: "Kamar Mandi",
        sub: [
          { text: "Dispenser Odol" },
          { text: "Ember & Baskom" },
          { text: "Gantungan Handuk" },
          { text: "Gayung" },
          { text: "Handuk & Kimono Mandi" },
          { text: "Kamar Mandi Lainnya" },
          { text: "Shower Curtain" },
          { text: "Tempat Sabun" },
          { text: "Tempat Sikat Gigi" },
          { text: "Toilet Cover" },
        ],
      },
      {
        text: "Kamar Tidur",
        sub: [
          { text: "Bantal Guling" },
          { text: "Bantal Kepala & Leher" },
          { text: "Kamar Tidur Lainnya" },
          { text: "Mattress Cover" },
          { text: "Sarung Bantal" },
          { text: "Selimut" },
          { text: "Sprei & Bed Cover" },
          { text: "Tempat Tidur" },
        ],
      },
      {
        text: "Kebersihan",
        sub: [
          { text: "Alat Pel" },
          { text: "Kain Lap" },
          { text: "Kebersihan Lainnya" },
          { text: "Kemoceng" },
          { text: "Pengharum Ruangan" },
          { text: "Pest Control" },
          { text: "Sapu" },
          { text: "Sikat" },
          { text: "Tempat Sampah" },
          { text: "Vacuum Cleaners" },
        ],
      },
      {
        text: "Laundry",
        sub: [
          { text: "Gantungan Baju" },
          { text: "Jemuran Baju" },
          { text: "Laundry Bag" },
          { text: "Laundry Lainnya" },
          { text: "Setrika" },
        ],
      },
      {
        text: "Ledeng",
        sub: [
          { text: "Filter Keran Air" },
          { text: "Keran Air" },
          { text: "Ledeng Lainnya" },
          { text: "Pembersih Saluran Air" },
          { text: "Pompa Air" },
        ],
      },
      {
        text: "Perawatan Hewan",
        sub: [
          { text: "Aksesoris Aquarium" },
          { text: "Aksesoris Hewan" },
          { text: "Aquarium" },
          { text: "Baju Hewan" },
          { text: "Grooming Hewan" },
          { text: "Hiasan Aquarium" },
          { text: "Kandang Hewan" },
          { text: "Mainan Hewan" },
          { text: "Makanan Hewan" },
          { text: "Obat Hewan" },
          { text: "Tempat Tidur Hewan" },
        ],
      },
      {
        text: "Rumah Tangga Lainnya",
      },
      {
        text: "Taman",
        sub: [
          { text: "Benih Bibit Tanaman" },
          { text: "Hiasan Taman" },
          { text: "Irigasi" },
          { text: "Media Tanam" },
          { text: "Peralatan Berkebun" },
          { text: "Pot Tanaman" },
          { text: "Pupuk" },
        ],
      },
      {
        text: "Tempat Penyimpanan",
        sub: [
          { text: "Botol" },
          { text: "Keranjang" },
          { text: "Kotak" },
          { text: "Laci" },
          { text: "Tempat Jam" },
          { text: "Tempat Obat" },
          { text: "Tempat Pakaian" },
          { text: "Tempat Penyimpanan Lainnya" },
          { text: "Tempat Perhiasan & Aksesoris" },
          { text: "Tempat Sepatu & Sandal" },
          { text: "Tempat Tas" },
          { text: "Tempat Tissue" },
          { text: "Travel Organizer" },
        ],
      },
    ],
  },
  {
    text: "Software",
  },
  {
    text: "Souvenir & Kado",
    sub: [
      {
        text: "Balon",
        sub: [
          { text: "Balon Huruf dan Angka" },
          { text: "Balon Karakter" },
          { text: "Balon Karet dan Latex" },
          { text: "Balon Lainnya" },
        ],
      },
      {
        text: "Boneka",
        sub: [
          { text: "Boneka Bantal" },
          { text: "Boneka Barbie" },
          { text: "Boneka Beruang" },
          { text: "Boneka Binatang" },
          { text: "Boneka Edukasi" },
          { text: "Boneka Karakter" },
          { text: "Boneka Lainnya" },
          { text: "Boneka Wisuda" },
        ],
      },
      {
        text: "Bunga",
        sub: [
          { text: "Buket Bunga" },
          { text: "Bunga Lainnya" },
          { text: "Bunga Papan" },
        ],
      },
      {
        text: "Bungkus dan Kemasan",
        sub: [
          { text: "Bubble Wrap" },
          { text: "Bungkus dan Kemasan Lainnya" },
          { text: "Kardus" },
          { text: "Kotak dan Kertas Kado" },
          { text: "Pita Kado" },
          { text: "Plastik" },
          { text: "Tas Kertas" },
        ],
      },
      {
        text: "Hadiah",
        sub: [
          { text: "Celengan" },
          { text: "Gantungan Kunci" },
          { text: "Hadiah Custom" },
          { text: "Hadiah Lainnya" },
          { text: "Kartu Ucapan" },
          { text: "Korek Api" },
          { text: "Magnet Kulkas" },
          { text: "Miniatur dan Karikatur" },
          { text: "Trophy dan Medali" },
          { text: "Uang Kuno" },
        ],
      },
      {
        text: "Kerajinan Tangan",
      },
      {
        text: "Lainnya",
      },
      {
        text: "Perlengkapan Pesta",
        sub: [
          { text: "Backdrop" },
          { text: "Banner" },
          { text: "Lampion" },
          { text: "Lilin" },
          { text: "Mahar dan Seserahan" },
          { text: "Perlengkapan Pesta Lainnya" },
          { text: "Piring dan Gelas Kertas" },
          { text: "Pompom" },
          { text: "Topeng" },
          { text: "Undangan" },
        ],
      },
      {
        text: "Souvenir",
        sub: [
          { text: "Hampers" },
          { text: "Souvenir Lainnya" },
          { text: "Souvenir Pernikahan" },
          { text: "Souvenir Ulang Tahun" },
          { text: "Voucher" },
        ],
      },
    ],
  },
  {
    text: "Uncategorized",
  },
];