export default {
    isShowStrikethrough:false,
    globalConversionSetting:'every',
    pageName: 'Checkout Page 1',
    templateType: 'RightSidebar',
    themeType: 'Classic',
    summaryPlacement:'Before Buy Button',
    backgroundColor: '#F6F8FC',
    titleForm: 'Data Penerima:',
    titleVariations: 'Pilihan Produk:',
    titlePayment: 'Metode Pembayaran:',
    titleBullet: 'Yang Anda Dapatkan:',
    titleShipping: 'Pengiriman:',
    headerImage: '',
    showTitle: false,
    showTagline: false,
    title: '',
    tagline: '',
    showProductImages: true,
    showRatingItemSold: false,
    showTestimonials: false,
    showOrderReview: true,
    showCreateOrder: true,
    showContentBullet: true,
    showSeals: true,
    showVideo: false,
    componentVideo: '',
    sealText: ['100Jaminan', 'Enkripsi'],
    variationSelectType: 'Modern',
    isLabel: 'hideLabel',
    formMode: 'Show All',
    initialFields: '',
    requestedFields: [{
        field: 'name',
        required: 'yes',
        active: true,
        label: 'Nama',
        placeholder: 'Nama Anda',
        value: '',
    },
    {
        field: 'phone',
        required: 'yes',
        active: true,
        label: 'No Handphone/WhatsApp',
        placeholder: 'No. WhatsApp Anda',
        value: '',
    },
    {
        field: 'email',
        required: 'no',
        active: false,
        label: 'Email',
        placeholder: 'Email Anda',
        value: '',
    },
    {
        field: 'quantity',
        required: 'no',
        active: false,
        label: 'Jumlah Pesanan',
        placeholder: 'Jumlah Pesanan',
        min: 1,
        max: 99,
        default: 1,
        value: '',
    },
    {
        field: 'note',
        required: 'no',
        active: false,
        label: 'Catatan',
        placeholder: 'Catatan',
        value: '',
    },
    {
        field: 'addressText',
        required: 'no',
        active: false,
        label: 'Alamat Lengkap',
        placeholder: 'Alamat Lengkap Anda',
        value: '',
    },
    {
        field: 'address',
        required: 'yes',
        active: false,
        label: 'Provinsi',
        placeholder: 'Pilih Provinsi',
        value: '',
        key: 'PROVINCE_NAME',
    },
    {
        field: 'address',
        required: 'yes',
        active: false,
        label: 'Kota/Kabupaten',
        placeholder: 'Pilih Kota/Kabupaten',
        value: '',
        key: 'CITY_NAME',
    },
    {
        field: 'address',
        required: 'yes',
        active: false,
        label: 'Kecamatan',
        placeholder: 'Pilih Kecamatan',
        value: '',
        key: 'DISTRICT_NAME',
    },
    {
        field: 'address',
        required: 'yes',
        active: false,
        label: 'Kota / Kecamatan',
        placeholder: 'Masukkan Kota / Kecamatan',
        value: '',
        key: 'ENTER_CITY_NAME',
    },
    ],
    isSaveInfoNextTime: false,
    addShipping: false,
    showBumpProduct: false,
    showBumpProductStep1: false,
    buyButtonChild: {},
    fieldsPositionMobile: [
        {
            name: "guaranteeSeal",
            label: "Guarantee Seals",
            showHideButton: true,
            buttonVar: "showSeals",
            showSeals: true,
            edit: true
        },
        {
            name: "productImage",
            label: "Product Image",
            showHideButton: true,
            buttonVar: "showProductImages",
            showProductImages: true
        },
        {
            name: "componentVideo",
            label: "Video",
            showHideButton: true,
            buttonVar: "showVideo",
            showVideo: false,
            edit: true
        },
        {
          name: "content_bullets",
          label: "Content and Bullet Point",
          showHideButton: true,
          buttonVar: "showContentBullet",
          showContentBullet: true,
          edit: true,
        },
        {
            name: "productDetails",
            label: "Product Select Variation"
        },
        {
            name: "requestedFields",
            label: "Requested Field",
        },
        {
            name: "shipping",
            label: "Shipping",
            showHideButton: true,
            buttonVar: "addShipping",
            addShipping : false,
            edit: true
        },
        {
            name: "saveThisInformation",
            label: "Save This Information",
            showHideButton: true,
            buttonVar: "isSaveInfoNextTime",
            isSaveInfoNextTime : false,
            edit: true,
        },
        {
            name: "payment",
            label: "Payment",
            edit: true
        },        
        {
            name: "bump",
            label: "Bump",
            showHideButton: true,
            buttonVar: "showBumpProduct",
            showBumpProduct : false
        },
        {
            name: "buyButton",
            uniqueName: "buyButton",
            label: "Buy Now Button",
            duplicate: true,
            parent: true,
            id: 1,
            edit: true,
        },
        {
            name: "orderSummary",
            label: "Order's Summary",
            showHideButton: true,
            buttonVar: "orderSummary",
            orderSummary: false,
        },
        {
            name: "otherContent",
            label: "Other Text",
            showHideButton: true,
            buttonVar: "showOtherContent",
            showOtherContent: false,
            edit: true
        },
    ],
    dropship: false,
    coupon: false,
    boldBuyButtonText: false,
    isAddIcon: false ,
    floatingButton: false,
    selectedIconName: 'chevron-right',
    selectedSplit: 'regular',
    buyButtonFontSize: "Medium",
    buyButtonText: 'Beli Sekarang',
    buyButtonStyle: '#04ac0d',
    video: false,
    content: "",
    otherContentTitle: "",
    otherContent: "",
    showOtherContent: false,
    bullets: [
        { name: 'Fitur yang pertama' },
        { name: 'Fitur yang kedua' }
    ],
    orderSummary: false,
    testimonials: [],
    pixelsFB: [],
    pixelsEventsFB: [],
    GTM: [],
    pixelsTiktok: [],

    whenComplete: 'successPage',
    customUrl: '',
    numbersWA: [{ number: '' }],
    successShowTitle: false,
    successShowChatButton: false,
    successTitle: '',
    successHeadline: 'Terimakasih sudah melakukan order {{product_name}}',
    successVideo: '',
    successTextBank: `
    <p>{{success-text-bank}}</p> 
    <p>{{total_price}}</p> 
    <p>kesalah satu bank berikut ini: </p> 
    <p>{{bank_accounts}}</p> 
    <p>{{footer}}</p> 
    <p>{{payment_link}}</p> `,
    successTextEpayment: `{{epay-text}}`,
    successTextCod: `
    <p>{{cod-header-text}}</p> 
    <p>{{cod-text}}</p>  
    <p>{{total_price}}</p> 
    <p>{{cod-text}}</p> 
    `,
    successpixelsFB: [],
    successpixelsEventsFB: [],
    successGTM: [],
    successpixelsTiktok: [],
    settingRedirectMessage:"By proceeding, you will get redirected to your checkout form",
    shippingHideView:false,
    paymentHideView:false,
    enableExcludeShipping:false,
    enableSettingRedirect:false,
    excludeShipping:"exclude",
    excludeShippingLocation:[],
    shippingDiscount: {
        status:false,
        type: "fixed",
        value: 0
    },
    saveInfoLabel: 'Save this information for next time',
    saveInfoWithoutEnable: false,
    tuktukThemeSetting: {
        ratingDesign: 'Star',
        ratingColor: '#F6D14B',
        maxRatingValue: '5',
        currentRatingValue: '',
        numberOfUsers: '',
        itemSoldAmount: '',
        isCheckoutNameAsProduct:false
    }
}